const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.bound,
		C3.Behaviors.LOS,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.MoveTo,
		C3.Plugins.shadowlight,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Plugins.Button,
		C3.Plugins.Dictionary,
		C3.Plugins.iframe,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.JavaScriptInEvents.Title_Event1_Act15,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Tilemap.Exps.TileWidth,
		C3.Plugins.Tilemap.Exps.TileHeight,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Exps.NodeXAt,
		C3.Behaviors.Pathfinding.Exps.NodeCount,
		C3.Behaviors.Pathfinding.Exps.NodeYAt,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Behaviors.Pathfinding.Cnds.OnFailedToFindPath,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Pathfinding.Acts.SetRotateSpeed,
		C3.Behaviors.Pathfinding.Acts.Stop,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Pin.Acts.SetDestroy,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.JavaScriptInEvents.Hunterassassin_Event145_Act6,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Tween: 0},
	{title1: 0},
	{Dhurandar_title: 0},
	{index: 0},
	{bullets: 0},
	{AJAX: 0},
	{BulletsPosition: 0},
	{Browser: 0},
	{Audio: 0},
	{Txt_Loading: 0},
	{jio_studio: 0},
	{b62: 0},
	{Sine: 0},
	{loading_dots: 0},
	{Txt_TapToStart: 0},
	{Touch: 0},
	{Solid: 0},
	{ShadowCaster: 0},
	{MapFloor: 0},
	{Pathfinding: 0},
	{BoundToLayout: 0},
	{LineOfSight: 0},
	{"8Direction": 0},
	{Player_Idel: 0},
	{Player_Walk: 0},
	{pathLine: 0},
	{Created: 0},
	{walkingTile: 0},
	{PathArray: 0},
	{Blade: 0},
	{BladeSmoother: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{SoldireBlue: 0},
	{Direction: 0},
	{Movement: 0},
	{Killed: 0},
	{PointA_X: 0},
	{PointA_Y: 0},
	{PointB_X: 0},
	{PointB_Y: 0},
	{NodeX: 0},
	{NodeY: 0},
	{MoveTo: 0},
	{Enemy1: 0},
	{Pin: 0},
	{ShadowLight: 0},
	{FOV: 0},
	{MapFloor2: 0},
	{WireConnect: 0},
	{dummpPlayer: 0},
	{Active: 0},
	{Checkpoint: 0},
	{EnemiesPath: 0},
	{Bullet: 0},
	{bullet_gun: 0},
	{InterstitialScreen: 0},
	{Interstitial_board: 0},
	{Interstitial_title_txt: 0},
	{Interstitial_text: 0},
	{Interstitial_text_array_game: 0},
	{button_1: 0},
	{button_2: 0},
	{button1_txt: 0},
	{button2_txt: 0},
	{Button_ShootButton: 0},
	{Button_UP: 0},
	{Button_Down: 0},
	{Button_Left: 0},
	{Button_Right: 0},
	{black: 0},
	{MapMatchLines: 0},
	{BTN_Dummy1: 0},
	{pipe_yellow: 0},
	{pipe_red: 0},
	{pipe_green: 0},
	{blue_node: 0},
	{blue_start_pipe: 0},
	{blue_turn: 0},
	{blue_mid_pipe: 0},
	{lines_array: 0},
	{active_grid: 0},
	{BlueLine: 0},
	{SniperBG: 0},
	{SniperEnemy2: 0},
	{SniperEnemy1: 0},
	{sniper_player: 0},
	{sniper_scope: 0},
	{Sniper_zoom_window: 0},
	{HUD: 0},
	{EnemyCount_txt: 0},
	{heart: 0},
	{HudBullet: 0},
	{TimerText: 0},
	{Hint1: 0},
	{iframe: 0},
	{LocalStorage: 0},
	{Hint2: 0},
	{Enemy_Killed_State: 0},
	{countdown_timer: 0},
	{bullet_gun_enemy: 0},
	{CheckPoint_1_Bubble: 0},
	{CheckPoint_2_Bubble: 0},
	{Caster: 0},
	{bullet_index: 0},
	{Splash_State: 0},
	{TargetX: 0},
	{TargetY: 0},
	{PreviousX: 0},
	{PreviousY: 0},
	{TileWidth: 0},
	{TileHeight: 0},
	{playerHealth: 0},
	{PreviousEnemyCount: 0},
	{Game_State: 0},
	{StartTimer: 0},
	{Timer: 0},
	{EnemyCount: 0},
	{CheckPoints: 0},
	{Interstitial_index: 0},
	{RandomNumber: 0},
	{tempDistance: 0},
	{tempAngle: 0},
	{StartX: 0},
	{nodeX: 0},
	{nodeY: 0},
	{StartY: 0},
	{CurrentTouchX: 0},
	{CurrentTouchY: 0},
	{linePreviousX: 0},
	{linePreviousY: 0},
	{LineAngle: 0},
	{activeNode: 0},
	{LineDistance: 0},
	{LineIndex: 0},
	{LastUID: 0},
	{GridX: 0},
	{GridY: 0},
	{color: 0},
	{LevelEnemies: 0},
	{BulletCount: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	title1: class extends self.ISpriteInstance {},
	Dhurandar_title: class extends self.ISpriteInstance {},
	bullets: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	BulletsPosition: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Txt_Loading: class extends self.ITextInstance {},
	jio_studio: class extends self.ISpriteInstance {},
	b62: class extends self.ISpriteInstance {},
	loading_dots: class extends self.ISpriteInstance {},
	Txt_TapToStart: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	MapFloor: class extends self.ITilemapInstance {},
	Player_Idel: class extends self.ISpriteInstance {},
	Player_Walk: class extends self.ISpriteInstance {},
	pathLine: class extends self.ISpriteInstance {},
	walkingTile: class extends self.ISpriteInstance {},
	PathArray: class extends self.IArrayInstance {},
	Blade: class extends self.ISpriteInstance {},
	BladeSmoother: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	SoldireBlue: class extends self.ISpriteInstance {},
	Enemy1: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	FOV: class extends self.ISpriteInstance {},
	MapFloor2: class extends self.ITilemapInstance {},
	WireConnect: class extends self.ITilemapInstance {},
	dummpPlayer: class extends self.ISpriteInstance {},
	Checkpoint: class extends self.ISpriteInstance {},
	EnemiesPath: class extends self.IArrayInstance {},
	bullet_gun: class extends self.ISpriteInstance {},
	InterstitialScreen: class extends self.ISpriteInstance {},
	Interstitial_board: class extends self.ISpriteInstance {},
	Interstitial_title_txt: class extends self.ITextInstance {},
	Interstitial_text: class extends self.ITextInstance {},
	Interstitial_text_array_game: class extends self.IArrayInstance {},
	button_1: class extends self.ISpriteInstance {},
	button_2: class extends self.ISpriteInstance {},
	button1_txt: class extends self.ITextInstance {},
	button2_txt: class extends self.ITextInstance {},
	Button_ShootButton: class extends self.ISpriteInstance {},
	Button_UP: class extends self.ISpriteInstance {},
	Button_Down: class extends self.ISpriteInstance {},
	Button_Left: class extends self.ISpriteInstance {},
	Button_Right: class extends self.ISpriteInstance {},
	black: class extends self.ISpriteInstance {},
	MapMatchLines: class extends self.ITilemapInstance {},
	BTN_Dummy1: class extends self.IButtonInstance {},
	pipe_yellow: class extends self.ISpriteInstance {},
	pipe_red: class extends self.ISpriteInstance {},
	pipe_green: class extends self.ISpriteInstance {},
	blue_node: class extends self.ISpriteInstance {},
	blue_start_pipe: class extends self.ISpriteInstance {},
	blue_turn: class extends self.ISpriteInstance {},
	blue_mid_pipe: class extends self.ISpriteInstance {},
	lines_array: class extends self.IArrayInstance {},
	active_grid: class extends self.IDictionaryInstance {},
	BlueLine: class extends self.ISpriteInstance {},
	SniperBG: class extends self.ISpriteInstance {},
	SniperEnemy2: class extends self.ISpriteInstance {},
	SniperEnemy1: class extends self.ISpriteInstance {},
	sniper_player: class extends self.ISpriteInstance {},
	sniper_scope: class extends self.ISpriteInstance {},
	Sniper_zoom_window: class extends self.ISpriteInstance {},
	HUD: class extends self.ISpriteInstance {},
	EnemyCount_txt: class extends self.ITextInstance {},
	heart: class extends self.ISpriteInstance {},
	HudBullet: class extends self.ISpriteInstance {},
	TimerText: class extends self.ITextInstance {},
	Hint1: class extends self.ITextInstance {},
	iframe: class extends self.IIframeInstance {},
	LocalStorage: class extends self.IInstance {},
	Hint2: class extends self.ITextInstance {},
	Enemy_Killed_State: class extends self.IArrayInstance {},
	countdown_timer: class extends self.ISpriteInstance {},
	bullet_gun_enemy: class extends self.ISpriteInstance {},
	CheckPoint_1_Bubble: class extends self.ISpriteInstance {},
	CheckPoint_2_Bubble: class extends self.ISpriteInstance {},
	Caster: class extends self.ISpriteInstance {}
}